### ISSUE TITLE
Couldn't connect to the app.swaggerhub.com from VS code SwaggerHub extension

### ISSUE THREAD

**Issue by Pritha-Redapple** [SmartBear/vscode-swaggerhub-release#15]
The following error showing:

invalid json response body at https://app.swaggerhub.com/apis/xxxxxxxx?page=0&limit=100&sort=NAME&order=ASC reason: Unexpected token < in JSON at position 0

**Comment by tmaguiresmartbear** [comment]
In the settings, connect to `api.swaggerhub.com` rather than `app.swaggerhub.com`
