### ISSUE TITLE
Unable to verify the first certificate

### ISSUE THREAD

**Issue by abahmueller** [SmartBear/vscode-swaggerhub-release#19]
After going into the settings for the extension, I am presented with an error stating that 'Unable to verify the first certificate".  When I cut and paste the request into my browser, the request succeeds and I am presented with a list of APIs.  Which certificate is causing the problem and how do I go about fixing this?

**Comment by hkosova** [comment]
@abahmueller Do you use SwaggerHub On-Premise? If so, please see: https://github.com/SmartBear/vscode-swaggerhub-release/issues/6#issuecomment-728925172

**Comment by abahmueller** [comment]
Helen,

Yes, I'm working in an on-premise environment.  Let me look at #6 and see what I can find out.

Thank you,
Andy
________________________________

**Comment by abahmueller** [comment]
SwaggerHub was just updated with the latest release so that should not be the issue at this point.  I am still receiving the error regarding not being able to load the first certificate.  When I look at the SwaggerHub admin console, the first certificate is the SwaggerHub Main Cert.  The attached screenshot shows that it's installed in my laptop's store.
![Swagger cert store](https://user-images.githubusercontent.com/81765320/157282753-4fbe2711-8367-440f-996e-23640a3e435a.png)

What else should I be looking at?

**Comment by abahmueller** [comment]
I am still receiving the "Unable to verify the first certificate" error in VS Code.  I have verified that both of the SwaggerHub certificates are installed in my laptop's certificate store.  What else can I look at?

**Comment by abahmueller** [comment]
I am still having the issue that I first reported.  Should I open a new issue or can someone review this one?

**Comment by abahmueller** [comment]
Closing this issue without resolution
