### ISSUE TITLE
How to access SwaggerHub on-premise instance secured via Azure AD SSO

### ISSUE THREAD

**Issue by filiphamdnb** [SmartBear/vscode-swaggerhub-release#3]
Updated:
Whenever you secure your SwaggerHub (on premise) setup behind a secured Proxy, like Azure Application Proxy with a security profile for oAuth, the plugin will fail to authenticate as it does not handle oauth (or other flows) before hitting swaggerhub. The only way to use this plugin now is if your SwaggerHub on premise is accessible via direct network connection or public dns without security proxy from the machine running vscode. 

This is the error I get currently: 
https://login.microsoftonline.com/4cbfea0a-b872-47f0-b51c-1c64953c3f0b/oauth2/authorize?response_type=code&client_id=c6826fdb-1957-40ba-9d94-4b58edbc7cc6&scope=openid&nonce=b3c4b720-baa3-4b96-bb64-309b86f8ab03&redirect_uri=https%3a%2f%2fswaggerhub.tech.dnb.no%2f&state=AppProxyState%3a%7b%22InvalidTokenRetry%22%3atrue%2c%22IsMsofba%22%3afalse%2c%22OriginalRawUrl%22%3a%22https%3a%5c%2f%5c%2fswaggerhub.tech.dnb.no%5c%2fapis%5c%2fDomainAPIs%3fpage%3d0%26limit%3d100%26sort%3dNAME%26order%3dASC%22%2c%22RequestProfileId%22%3a%22eb9ae144-3864-4621-a3a2-a333d5798e13%22%7d%23EndOfStateParam%23&client-request-id=b3c438de-8cbd-46b1-9fb0-b9e830d5e919 reason: Unexpected token < in JSON at position 4

**Comment by tmaguiresmartbear** [comment]
Hi @filiphamdnb I know we spoke about this and this is related to your networking.  Have you found discovered a workaround with your infosec team?

**Comment by filiphamdnb** [comment]
No solution as of yet. I am trying out the azure account extension to enable login and authentication in vscode before running this extension, but so far the response in vscode swaggerhubis the error above, while the same url in a browser lists all APIs in the configured domains. 

The only way around it i see is building something that adds the http header token to all outgoing calls from swaggerhub extension, or you can add a config setting so that users can add custom headers.
