### ISSUE TITLE
SwaggerHub UI is reading new API versions (OAS 3.0.0) created with VS plugin as swagger 2.0

### ISSUE THREAD

**Issue by adrianmin** [SmartBear/vscode-swaggerhub-release#5]
I have created new versions of API's definitions (OAS 3.0.0) using the Swaggerhub VS plugin and the new versions are created successfully but when I try to access the new version in SwaggerHub, it asks me to convert it to OAS 3.0.0 or remain at Swagger 2.0. I can see that the definition is OAS 3.0.0 but it appears to be reading it as Swagger 2.0.

**Comment by ben-smartbear** [comment]
Hi @adrianmin , thanks for the report!

This has been resolved as of the 1.0.2 version. It will be available through the auto-updater very soon, or you can head to the marketplace to get the new version right now: https://marketplace.visualstudio.com/items?itemName=SmartBearSoftware.vscode-swaggerhub
