### ISSUE TITLE
On-Premise certificate error

### ISSUE THREAD

**Issue by yondersever** [SmartBear/vscode-swaggerhub-release#6]
I'am getting following error when I refresh apis and domains. Because of that error list is not filled.

Error:

request to (url) failed, reason: unable to verify the first certificate

**Comment by photchkiss** [comment]
Getting the same error. I am wondering if there is a way to provide a cafile or something that includes certificates not signed by a Global CA?

**Comment by hkosova** [comment]
[This answer](https://stackoverflow.com/a/63108196) suggests adding the trusted certificates (root + intermediate) to the operating system's certificate store:

>According to https://code.visualstudio.com/docs/setup/network, the solution is to edit the system certificate store:
>> Since Chromium uses the OS's certificate trust infrastructure, the preferred option is to add your proxy's certificate to your OS's trust chain.
>
> This means that your answer is OS-dependent:
> * Windows: Powershell [`Import-Certificate`](https://docs.microsoft.com/en-us/powershell/module/pkiclient/import-certificate?view=win10-ps) or the GUI equivalent
> * Mac: Via [Keychain Access](https://support.untangle.com/hc/en-us/articles/212220648-Manually-installing-root-certificate-on-Mac-OSX)
> * NSS under linux - it is unclear *which* NSS database it uses. `certutil` is used to edit them.


Can you try and see if this resolves the issue?

**Comment by yondersever** [comment]
> [This answer](https://stackoverflow.com/a/63108196) suggests adding the trusted certificates (root + intermediate) to the operating system's certificate store:
> 
> > According to https://code.visualstudio.com/docs/setup/network, the solution is to edit the system certificate store:
> > > Since Chromium uses the OS's certificate trust infrastructure, the preferred option is to add your proxy's certificate to your OS's trust chain.
> > 
> > 
> > This means that your answer is OS-dependent:
> > 
> > * Windows: Powershell [`Import-Certificate`](https://docs.microsoft.com/en-us/powershell/module/pkiclient/import-certificate?view=win10-ps) or the GUI equivalent
> > * Mac: Via [Keychain Access](https://support.untangle.com/hc/en-us/articles/212220648-Manually-installing-root-certificate-on-Mac-OSX)
> > * NSS under linux - it is unclear _which_ NSS database it uses. `certutil` is used to edit them.
> 
> Can you try and see if this resolves the issue?

It solved my problem.
Thanks for your help.
