### ISSUE TITLE
Response headers for Try it Out differ on VS Code to the SH web app

### ISSUE THREAD

**Issue by savage-alex** [SmartBear/vscode-swaggerhub-release#8]
I was using the Try it out in conjunction with a POST endpoint that returns a location header with a 201 and noticed that the SwaggerUI in the VSCode extension shows different results to what is shown on the web app (Crucially the header I have added is missing)
![SwaggerHub VSCode Try It Out Issue](https://user-images.githubusercontent.com/25430683/99395728-c1899b80-28d8-11eb-82b2-86244250649b.PNG)

**Comment by tmaguiresmartbear** [comment]
Hi @savage-alex 
This is because SwaggerHub adds extra headers as a result of going through a proxy so we don't run into CORS issues.
A more in depth explanation is in the Swagger-ui project here: https://github.com/swagger-api/swagger-ui/issues/3340#issuecomment-313550973
